language: python
python:
  # Python **2.6** and **3.3** are no more supported
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7"     # Not available yet (Unable to download 3.7 archive).
  - "3.7-dev"   # 3.7 development branch
  - "nightly"   # currently points to 3.7-dev
  # - "pypy"    # some unit tests fail
install:
  - pip install tox-travis
  - pip install coveralls
script:
  tox
after_success:
  coveralls
